services:
  bank-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - API_URL=http://host.docker.internal:3000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
